volumes:
  mysql_log_data:
    driver: local
  mysql_lib_data:
    driver: local
  redis_data:
    driver: local
  www_data:
    driver: local
  bxtemp_data:
    driver: local
  msmtp_data:
    driver: local
  browscap_data:
    driver: local
  geoip2_data:
    driver: local
  ssl_data:
    driver: local

services:
  memcached:
    image: memcached:1.6.39-alpine
    container_name: dev_memcached
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "11211:11211"
    init: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - memcached

  redis:
    image: redis:7.2.10-alpine
    container_name: dev_redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    init: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - redis

  mysql:
    image: quay.io/bitrix24/percona-server:8.0.43-v1-rhel
    #image: quay.io/bitrix24/percona-server:8.4.5-v1-rhel
    container_name: dev_mysql
    restart: unless-stopped
    env_file:
      - .env
      - .env_sql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_log_data:/var/log/mysql
      - mysql_lib_data:/var/lib/mysql
    init: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - SYS_NICE
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - mysql

  php:
    image: quay.io/bitrix24/php:8.2.29-fpm-v1-alpine
    #image: quay.io/bitrix24/php:8.3.25-fpm-v1-alpine
    #image: quay.io/bitrix24/php:8.4.12-fpm-v1-alpine
    container_name: dev_php
    restart: unless-stopped
    env_file:
      - .env
      - .env_php
    ports:
      - "9000:9000"
    volumes:
      - ./confs/php82/etc/:/usr/local/etc/
      #- ./confs/php83/etc/:/usr/local/etc/
      #- ./confs/php84/etc/:/usr/local/etc/
      - ./html:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - msmtp_data:/opt/msmtp/
      - browscap_data:/opt/browscap/
      - geoip2_data:/opt/geoip2/
      - ssl_data:/ssl/
    init: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - php
    depends_on:
      - mysql
      - memcached

  nginx:
    image: quay.io/bitrix24/nginx:1.28.0-v2-alpine
    container_name: dev_nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8588:80"
      - "8589:443"
    volumes:
      - ./confs/nginx/:/etc/nginx/
      - ./html:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - ssl_data:/ssl/
    init: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - nginx
    depends_on:
      - php

networks:
  dev:
    driver: bridge
    attachable: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24